### ISSUE TITLE
Loss of site functionality and console errors.

### ISSUE THREAD

**Issue by Ray-Adams** [TheTypingMatch/ttm-release-log#1]
## Description
[TheTypingMatch.com](http://thetypingmatch.com) is currently only showing the [linear-gradient background image](#image), and none of the other previous contents of the site, such as the page layout and article submission form. Firefox, Chrome, and Safari all have the same results. When I checked the developer console, I received the following errors as shown below.

## Console Errors
<img width="1440" alt="Screen Shot 2020-06-02 at 7 25 53 PM" src="https://user-images.githubusercontent.com/63924749/83591864-d088b700-a50d-11ea-8696-89854c229c00.png">

<a name="image" />
<h2>TTM Full-Page Image</h2>
<img width="1440" alt="Screen Shot 2020-06-02 at 7 27 55 PM" src="https://user-images.githubusercontent.com/63924749/83591606-2b6dde80-a50d-11ea-883a-8d6044eff72c.png">

**Comment by Le-SirH** [comment]
Indeed. There seems to be some issues with the SCSS compile script. I will be looking into it. Thanks!

**Comment by Ray-Adams** [comment]
I just checked the site on Safari, Chrome, and Firefox, and everything seems to be functioning as usual, however, on the _Article Submission Page_, the "Submit" button is partially cut-off (see image below) on Chrome and Firefox, while Safari shows the entire button. Also, scrolling seems to be disabled (for the _Article Submission Page_) on all three of the browsers mentioned above.

<img width="1440" alt="Screen Shot 2020-06-11 at 1 14 28 PM" src="https://user-images.githubusercontent.com/63924749/84434906-b6259c00-abe5-11ea-9a78-49b69c231dc6.png">

**Comment by Le-SirH** [comment]
Thanks for the info!

**Comment by Ray-Adams** [comment]
I'm glad I was able to help!

**Comment by Ray-Adams** [comment]
It looks like this issue has been resolved, as I just tested it on Safari, Firefox, and Chrome. Thanks!
